version: 2.1

jobs:
  lint:
    steps:
      - run:
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile

workflows:
  version: 2
  test:
    jobs:
      - lint