version: 2.1

jobs:
  lint-dockerfile:
    executor: docker
    steps:
      - checkout
      - run:
          name: Run Hadolint
          command: |
            curl -sSL -o /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
            hadolint Dockerfile

workflows:
  karsajobs-ui:
    jobs:
      - lint-dockerfile