version: 2.1
orbs:
  docker: docker

jobs:
  lint-dockerfile:
    steps:
      - run:
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
    
workflows:
  version: 2
  karsajobs-ui:
    jobs:
      - lint-dockerfile
