version: 2.1
orbs:
  docker: circleci/docker@2.1.0

jobs:
  lint-dockerfile:
    executor: docker
    steps:
      - run:
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
    
workflows:
  version: 2
  karsajobs-ui:
    jobs:
      - lint-dockerfile
