version: 2.1

executors:
  docker:
    docker:
      - image: docker

jobs:
  test-app:
    docker:
      - image: cimg/go:1.15.10
    steps:
      - checkout
      - run:
          name: Test App
          command: |
            go test -v -short --count=1 $(go list ./...)

workflows:
  karsajobs-ui:
    jobs:
      - test-app