version: 2.1

jobs:
  lint-dockerfile:
    steps:
      - checkout
      - run:
          name: Run Hadolint
          command: |
            curl -sSL -o /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
            hadolint Dockerfile