version: 2.1
orbs:
  docker: circleci/docker@2.1.0

workflows:
  version: 2
  lint-dockerfile:
    jobs:
      steps:
        - run:
            name: Run Lint Dockerfiles
            dockerfiles: Dockerfile

