version: 2.1

jobs:
  karsajobs-ui:
    steps:
      - run:
        name: lint-dockerfile
        command: docker run --rm --interactive hadolint/hadolint < Dockerfile

workflows:
  version: 2
  test:
    jobs:
      - karsajobs-ui