version: 2.1

executors:
  docker:
    docker:
      - image: docker

jobs:
  build-app-karsajobs-ui:
    executor: docker
    steps:
      - run:
          name: Build App
          command: |
            docker build -t stevensama73/karsajobs-ui:latest .
            docker tag stevensama73/karsajobs-ui:latest ghcr.io/stevensama73/karsajobs-ui:latest
            export CR_PAT='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'
            echo $CR_PAT | docker login ghcr.io -u stevensama73 --password-stdin
            docker push ghcr.io/stevensama73/karsajobs-ui:latest

workflows:
  karsajobs-ui:
    jobs:
      - build-app-karsajobs-ui
