version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: docker:17.06.1-ce-git
    steps:
      - run:
          name: Run Hadolint
          command: |
            apk update && apk add curl curl-dev bash

workflows:
  karsajobs-ui:
    jobs:
      - lint-dockerfile
