version: 2.1

jobs:
  lint-dockerfile:
    docker:
      image: docker:stable
    steps:
      - run:
          name: Run Hadolint
          command: |
            curl -sSL /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
            hadolint Dockerfile

workflows:
  test:
    jobs:
      - lint-dockerfile
