version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: docker:17.06.1-ce-git
    steps:
      - checkout
      - run:
          name: Run Hadolint
          command: |
            apt-get install curl
            curl -sSL /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
            hadolint Dockerfile

workflows:
  karsajobs-ui:
    jobs:
      - lint-dockerfile
