name: Mongo Item App Docker Image

on:
  push:
    branches:
      - proyek-pertama
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      
      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/micro/item-app:1.0
          docker push ghcr.io/micro/item-app:1.0