name: Mongo Item App Docker Image

on:
  push:
    branches:
      - proyek-pertama
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      
      - name: 'Build Image'
        run: |
          docker build -t item-app:v1 .
          docker tag item-app:v1 ghcr.io/stevensama73/item-app:v1
          docker push ghcr.io/stevensama73/item-app:v1