name: Mongo Item App Docker Image

on:
  push:
    branches:
      - proyek-pertama
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: stevensama73
          password: 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
      
      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/stevensama73/item-app:1.0
          docker push ghcr.io/stevensama73/item-app:1.0